import Head from "next/head";
import Blockbiru from "../components/Blockbiru";
import Faq from "../components/Faq";
import Footer from "../components/Footer";
import Jumbotron from "../components/Jumbotron";
import Navbar from "../components/Navbar";
import OurServices from "../components/OurServices";
import Testimonial from "../components/Testimonial";
import WhyUs from "../components/WhyUs";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Binar Car Rental</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Jumbotron />
      <OurServices />
      <WhyUs />
      <Testimonial />
      <Blockbiru />
      <Faq />
      <Footer />
    </div>
  );
}
