import { Form } from "antd";
import axios from "axios";
import Head from "next/head";
import React, { useState } from "react";
import CarList from "../components/CarList";
import Footer from "../components/Footer";
import Jumbotron from "../components/Jumbotron";
import Navbar from "../components/Navbar";
import SearchBar from "../components/SearchBar";

const Search = () => {
  const [cars, setCars] = useState(null);

  const [form] = Form.useForm();

  const onFinish = async (value) => {
    if (!value.name) {
      delete value.name;
    }
    if (!value.category) {
      delete value.category;
    }
    if (!value.minPrice) {
      delete value.minPrice;
    }
    if (!value.maxPrice) {
      delete value.maxPrice;
    }
    if (!value.isRented) {
      delete value.isRented;
    }
    const params = new URLSearchParams(value).toString();

    const { data } = await axios.get(
      `https://bootcamp-rent-cars.herokuapp.com/customer/v2/car?${params}`
    );
    setCars(data.cars);
  };

  return (
    <div>
      <Head>
        <title>Searh Car</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Jumbotron />
      <Form form={form} onFinish={onFinish}>
        <SearchBar />
      </Form>
      <CarList cars={cars} />
      <Footer />
    </div>
  );
};

export default Search;
