import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import Container from "../../../components/Container";
import DetailCard from "../../../components/DetailCard";
import Footer from "../../../components/Footer";
import Jumbotron from "../../../components/Jumbotron";
import Jumbotron2 from "../../../components/Jumbotron2";
import Navbar from "../../../components/Navbar";
import SearchBar from "../../../components/SearchBar";

const Mobil = () => {
  const router = useRouter();

  const [data, setData] = useState(null);

  const getCarID = async () => {
    const { data } = await axios.get(
      `https://bootcamp-rent-cars.herokuapp.com/customer/car/${router.query.id}`
    );
    setData(data);
  };

  useEffect(() => {
    if (router.query.id) {
      getCarID();
    }
  }, [router.query.id]);

  return (
    <>
      <Head>
        <title>Car Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Jumbotron2 />
      <SearchBar disabled={true} />
      <Container className="flex justify-around">
        <div
          className="flex flex-col gap-[16px] rounded-8px p-[24px]"
          style={{ boxShadow: "0px 0px 4px rgba(0, 0, 0, 0.15)" }}
        >
          <h1>Tentang Paket</h1>
          <h1>Include</h1>
          <ul className="font-bold text-[#8A8A8A]">
            <li>
              · Apa saja yang termasuk dalam paket misal durasi max 12 jam
            </li>
            <li>· Sudah termasuk bensin selama 12 jam</li>
            <li>· Sudah termasuk Tiket Wisata </li>
            <li>· Sudah termasuk pajak</li>
          </ul>
          <h1>Exclude</h1>
          <ul className="font-bold text-[#8A8A8A]">
            <li>· Tidak termasuk biaya makan sopir Rp 75.000/hari</li>
            <li>
              · Jika overtime lebih dari 12 jam akan ada tambahan biaya Rp
              20.000/jam
            </li>
            <li>·Tidak termasuk akomodasi penginapan</li>
          </ul>
          <h1>Refund, Reschedule, Overtime</h1>
          <ul className="font-bold text-[#8A8A8A]">
            <li>· Tidak termasuk biaya makan sopir Rp 75.000/hari</li>
            <li>
              · Jika overtime lebih dari 12 jam akan ada tambahan biaya Rp
              20.000/jam
            </li>
            <li>· Tidak termasuk akomodasi penginapan</li>
            <li>
              · Jika overtime lebih dari 12 jam akan ada tambahan biaya Rp
              20.000/jam
            </li>
            <li>· Tidak termasuk akomodasi penginapan</li>
          </ul>
        </div>
        <div>{data ? <DetailCard data={data} /> : null}</div>
      </Container>
      ;
      <Footer />
    </>
  );
};

export default Mobil;
